### ISSUE TITLE
Deadlock here?

### ISSUE THREAD

**Issue by gottlieb76** [cyber-crypt-com/encryptonize-core#109]
https://github.com/cyber-crypt-com/encryptonize-core/blob/8f9f998a9def902a3f31d31ae9da7569b4a33fc9/encryption-service/authstorage/authstorage.go#L123

**Comment by bruno-cc** [comment]
I close this ticket as it's not really a problem. The lock only happens when we panic between the creation of a new transaction and the deferred close call. This shouldn't not happen again as long as we don't add the panic causing programming error again.
