### ISSUE TITLE
ECCS: createuser make flag mandatory

### ISSUE THREAD

**Issue by bruno-cc** [cyber-crypt-com/encryptonize-core#142]
**User story**
As a user I find it confusing that ECCS allows it to create users without any flags. 
I want to the ECCS validates that at least one flag is set for the user
So that I don't create users that can't do anything.

**Acceptance Criteria**
- ECCS refuses to create user without flags

**Scope**
- ECCS command handling

**Not in Scope**
- NA

**Non-functional requirements**
- NA

**Additional context**
- NA

**Comment by gottlieb76** [comment]
PR #144
