### ISSUE TITLE
Authstorage circuit breaker opens when cancelling contexts during benchmarking

### ISSUE THREAD

**Issue by matas-cc** [cyber-crypt-com/encryptonize-core#188]
**Describe the bug**
When running benchmarker on encryptonize-core, with concurrency set to 32, after the first run times out and retrieve requests are cancelled, Auth storage circuit breaker opens and causes the second run to fail.

**To Reproduce**
1. Set concurrency to 32 in Encryptonize benchmarker's run_bench.sh
2. Run encryptonize with Docker containers 
3. Run benchmarker

**Expected behavior**

The first benchmarking run completes successfully, the following one however fails with an internal error.

**Additional context**
Possible solution could be to replace the currently used https://github.com/sony/gobreaker with
https://github.com/mercari/go-circuitbreaker , which would ignore failures from cancelled requests.

**Comment by Retler** [comment]
Ah, that's annoying. Perhaps circuit breaker can be disabled during in test/debug mode.

**Comment by gottlieb76** [comment]
sounds like a feature.. where does the CB trip? Inside ES or ..?

**Comment by matas-cc** [comment]
Yes in ES and benchmarker kills itself after getting back an internal error
