### ISSUE TITLE
Gated performance tests

### ISSUE THREAD

**Issue by gottlieb76** [cyber-crypt-com/encryptonize-core#51]
**Description**
We need to create a benchmark suite that monitors the performance of key functionality as well as the encryption core. This is to be executed as a gate before merge to master.

**Acceptance Criteria**
- Performance tests are run at merge to main and a threshold is set for when we diverge too much from the baseline. (maybe they are run, but are not blocking for merge)
- The results of the performance tests are sent to a storage to be aggregated and analyzed 
- The suite of benchmarks to run in this phase should be limited to a couple of minutes at most.

**Scope**
- Performance baseline
- Gated performance tests
- Analytics

**Not in Scope**
Improving performance

**Comment by philip-cc** [comment]
Closing this for now, we can always bring it back when performance is a more mature topic for us.
