### ISSUE TITLE
Trim down staging cluster

### ISSUE THREAD

**Issue by emil-muller** [cyber-crypt-com/encryptonize-core#57]
**Description**
Our staging cluster is currently costing us a lot of money. This is mainly due to our cockroachdb instance. We should therefore figure out if we're able to vertically down scale the cluster.

**Acceptance Criteria**
- The cluster is down scaled to the most cost efficient size.

**Scope**
Researching cockroachdbs hardware requirements and scaling the cluster.

**Not in Scope**
Performance concerns. With the amount of calls we make to the staging cluster, performance shouldn't be that important.

**Comment by philip-cc** [comment]
This is fixed in #248
