### ISSUE TITLE
RBAC: Investigate how we should use k8s RBAC in the context of Google Cloud IAM

### ISSUE THREAD

**Issue by Retler** [cyber-crypt-com/encryptonize-core#60]
There are several ways we can authorize accounts in GCP to have access to k8s resources through RBAC. This issue is about investigating pros/cons and settling on a way to do it. Possible proposes:

1. Create kubernetes role bindings to each Google Cloud account individually.

2. Create a Google Cloud Service Account and give it the role of operator or deployer. Give each of our Google Cloud accounts the "Service Account User" role so we can take on the role of deployer/operator temporarily through the Service Account.

3. Put all of our accounts in repective Google Groups (requires Gsuite or Cloud Identity) and provide a RoleBinding to the group. Then all users in the group will be authorized by the bounded role.

**Comment by philip-cc** [comment]
Now that we have experience with DOJO, this issue might be a bit stale. The general topic will likely fall under https://github.com/cyber-crypt-com/encryptonize-core/issues/55
