### ISSUE TITLE
"Remove user" handler

### ISSUE THREAD

**Issue by philip-cc** [cyber-crypt-com/encryptonize-core#62]
**Description**
We need handlers for removing normal users. It should use the admin authentication implemented in cyber-crypt-com/tmp#28. Not everything about this has been thought through yet. Some things to consider:
* Should it be possible to remove admin users?
* Should it be possible to remove user rights, i.e. remove just the admin rights of a user?

**Enabler for**
List issues that have direct customer value that this story enables, if any
- Issue cyber-crypt-com/tmp#5 

**Acceptance Criteria**
- A decision about how to implement this has been reached
- An admin can remove users according to the above decision.

**Scope**
Remove user handlers

**Not in Scope**
N/A

**Additional context**
N/A

**Tasks**
- [ ]  cyber-crypt-com/encryptonize-core#85
- [ ]  cyber-crypt-com/encryptonize-core#86

**Comment by bruno-cc** [comment]
@matas-cc I will finish up this PR 🙂
