### ISSUE TITLE
Implement the remove user funtionality

### ISSUE THREAD

**Issue by emil-muller** [cyber-crypt-com/encryptonize-core#64]
**Description**
We should implement the design agreed upon in cyber-crypt-com/tmp#63 

**Enabler for**
List issues that have direct customer value that this story enables, if any
- Issue cyber-crypt-com/tmp#62

**Acceptance Criteria**
- That the design agreed upon in cyber-crypt-com/tmp#63 works according to the spec
- Meaningful tests for the feature has been written

**Scope**
Implementation of the feature

**Not in Scope**
Design of the feature

**Comment by bruno-cc** [comment]
Closed as #62 #63 should be enough for that feature.
