### ISSUE TITLE
Introduce Token Expiry

### ISSUE THREAD

**Issue by iead-cc** [cyber-crypt-com/encryptonize-core#97]
**Description**
Our token currently contain everything required by the encryption server to perform its task and thus are very powerful. Manually revoking these token is not possible, this is unacceptable in cases where user shall be deleted or token got stolen. One meaningful solution to this is for the token to automatically expire after some time. This entails some changes to user creation as token need to be reissued for the same user.

**Enabler for**
- Issue https://github.com/cyber-crypt-com/encryptonize-premium/issues/5

**Acceptance Criteria**
- User can get fresh token after creation
- Token expire automatically
- Expired token are rejected by the API with Unauthenticated

**Scope**
- Authentication Server
- AuthenticatUser function

**Additional context**
The authentication server should first be split from the encryption server

**Tasks**
- [ ] Create "login" endpoint
- [ ] Add expiry to token

**Comment by philip-cc** [comment]
Rolled into https://github.com/cyber-crypt-com/encryptonize-core/issues/121
