### ISSUE TITLE
Performance: Basic performance numbers

### ISSUE THREAD

**Issue by gottlieb76** [cyber-crypt-com/encryptonize-core#98]
**Description**
We should defined and build a performance measurement tool that can answer the following questions:
- With encryptonize (isolated) what is the throughput in terms of 
    - latency as a function of package size
    - throughput: bytes/sec/core as a function of package size
    - concurrency: requests/sec/core as a function of package size
- With an underlying storage (S3 or Ceph), what is the relative overhead of Encryptonize compared to direct in terms of
    - increase in latency as a function of package size
    - decrease in throughput (bytes/sec/core) as a function of package size
- Some number that shows it can scale horizontally, for instance
    - fixed 1kb package size, fixed VM size (
        - latency as a function of cluster size
        - throughput: bytes/sec/core as a function of cluster size
        - concurrency: requests/sec/core as a function of cluster size

The metrics should be reported as:
- Latencies:
    - Percentiles (50, 75, 90, 95, 99, 99.9)
- Requests / Sec:
    - Avg, Stdev, Max (per sec)
- Throughput:
    - Avg, Stdev, Max (per sec)
- Success:
    - Percentage of successful requests
    - Breakdown of error codes (if applicable)

**Enabler for**
List issues that have direct customer value that this story enables, if any
- Issue #51 
- Presentation demo

**Acceptance Criteria**
- we are able to run the above tests from the commandline
- output into either a formatted ascii or JSON for easy consumption into a chart tool
- The sizes and sample sizes should be parameters to a run
- There exists a cluster (prod?, staging?, or on demand (spin-up)) that can be used to run the test against

**Scope**
- Either create a new CLI or add the functionality into an existing one (Bulwark?)
- Create data as text output from a CLI tool

**Not in Scope**
- Creating charts or graphics of the data
- baselining or storage of results

**Tasks**

**Comment by philip-cc** [comment]
I implemented a memory only version of the ES in #110 such that we can try to get a baseline.

**Comment by philip-cc** [comment]
Added a followup issue here: https://github.com/cyber-crypt-com/encryptonize-premium/issues/12
